if %letter%==A set answer=1
if %letter%==B set answer=2
if %letter%==c set answer=3
if %letter%==d set answer=4
if %letter%==e set answer=5
if %letter%==f set answer=6
if %letter%==g set answer=7
if %letter%==h set answer=8
if %letter%==i set answer=9
if %letter%==j set answer=10
if %letter%==k set answer=11
if %letter%==l set answer=12
if %letter%==m set answer=13
if %letter%==n set answer=14
if %letter%==o set answer=15
if %letter%==p set answer=16
if %letter%==q set answer=17
if %letter%==r set answer=18
if %letter%==s set answer=19
if %letter%==t set answer=20
if %letter%==u set answer=21
if %letter%==v set answer=22
if %letter%==x set answer=23
if %letter%==y set answer=24
if %letter%==z set answer=25