if %errorlevel%==1 set answer=A
if %errorlevel%==2 set answer=B
if %errorlevel%==3 set answer=C
if %errorlevel%==4 set answer=D
if %errorlevel%==5 set answer=E
if %errorlevel%==6 set answer=F
if %errorlevel%==7 set answer=G
if %errorlevel%==8 set answer=H
if %errorlevel%==9 set answer=I
if %errorlevel%==10 set answer=J
if %errorlevel%==11 set answer=k
if %errorlevel%==12 set answer=L
if %errorlevel%==13 set answer=M
if %errorlevel%==14 set answer=N
if %errorlevel%==15 set answer=O
if %errorlevel%==16 set answer=P
if %errorlevel%==17 set answer=Q
if %errorlevel%==18 set answer=R
if %errorlevel%==19 set answer=S
if %errorlevel%==20 set answer=T
if %errorlevel%==21 set answer=U
if %errorlevel%==22 set answer=V
if %errorlevel%==23 set answer=W
if %errorlevel%==24 set answer=X
if %errorlevel%==25 set answer=Y
if %errorlevel%==26 set answer=Z
if %errorlevel%==27 set answer=Æ
if %errorlevel%==28 set answer=Ø
if %errorlevel%==29 set answer=Å